model:
  base_learning_rate: 4.5e-06
  target: taming.models.vq_test.AutoencoderCodebook
  params:
    monitor: val/rec_loss
    embed_dim: 4
    quantizeconfig:
      target: taming.modules.vqvae.quantize_test.VectorQuantizeConstrain
      params:
        scale: 1
        partitions: 1
        n_e: 16384
        e_dim: 4
        beta: 0.25
    ddconfig:
      double_z: true
      z_channels: 4
      resolution: 256
      in_channels: 3
      out_ch: 3
      ch: 128
      ch_mult:
      - 1
      - 2
      - 4
      - 4
      num_res_blocks: 2
      attn_resolutions: []
      dropout: 0.0
    lossconfig:
      target: taming.modules.losses.vqperceptual.VQLPIPSWithDiscriminator
      params:
        disc_conditional: false
        disc_in_channels: 3
        disc_start: 30001
        disc_weight: 0.5
        codebook_weight: 0.01
        
data:
  target: main.DataModuleFromConfig
  params:
    batch_size: 5
    num_workers: 8
    train:
      target: taming.data.custom.CustomTrain
      params:
        training_images_list_file: /data1/lianjunrong/dataset/celeba-1024/train_list.txt
        size: 286
        crop_size: 256
    validation:
      target: taming.data.custom.CustomTest
      params:
        test_images_list_file: /data1/lianjunrong/dataset/celeba-1024/test_list.txt
        size: 256
        
lightning:
  trainer:
    devices: 8
    num_nodes: 1 
    strategy: ddp_find_unused_parameters_true
    accelerator: gpu
    max_epochs: 50
    precision: 32