from taming.modules.losses.vqperceptual import DummyLoss
from taming.modules.losses.contperceptual import LPIPSWithDiscriminator
from taming.modules.losses.contperceptual import LPIPSWithDiscriminatorCodebook
from taming.modules.losses.classification import ClassificationWithoutEncoder
